#!/bin/sh

: "${MOCK_IPTABLES_LOG:?MOCK_IPTABLES_LOG is required}"
printf 'ip6 %s\n' "$*" >>"$MOCK_IPTABLES_LOG"

case " $* " in
    *" -D "*" -j DROP "*) exit 0 ;;
    *" -D "*) exit 1 ;;
esac
exit 0
